
/// Generic Dimensions
//project tine mr 3
const MARGIN_SMALL = 4.0;
const MARGIN_MEDIUM = 8.0;
const MARGIN_CARD_MEDIUM_2 = 12.0;
const MARGIN_MEDIUM_2 = 16.0;
const MARGIN_MEDIUM_3 = 20.0;
const MARGIN_LARGE = 24.0;
const MARGIN_XLARGE = 32.0;
const MARGIN_XXLARGE = 48.0;

const TEXT_REGULAR = 14.0;
const TEXT_REGULAR_2X = 16.0;
const TEXT_REGULAR_3X = 20.0;
const TEXT_HEADING_1X = 24.0;
const TEXT_HEADING_2X = 24.0;
const TEXT_BIG = 32.0;

///App Specific
//di app htl mr pl 3
const BANNER_SECTION_HEIGHT = 200.0;
const BANNER_PLAY_BUTTON_SIZE = 56.0;
const MOVIE_LIST_HEIGHT = 270.0;
const SHOW_CASE_HEIGHT = 240.0;
const BEST_ACTOR_HEIGHT = 200.0;
const MOVIE_LIST_ITEM_WIDTH = 180.0;
const SHOWTIME_SECTION_HEIGHT = 180.0;
const MOVIE_DETAIL_SCREEN_SLIVER_APP_BAR_HEIGHT = 300.0;
const MOVIE_DETAIL_RATING_TEXT_SIZE = 56.0;
const MOVIE_VIEW_IMAGE_HEIGHT = 200.0;
const SHOW_CASE_SECTION_CONTAINER_WIDTH = 300.0;